Repository LikeLion-SKU/likelion-homepage-fe, pull requests merged in 2025-01, with the labels that each got.

#55 🚚 Rename : css파일 pages 폴더 내 같은 위치로 변경
  src/pages/AdminApply.module.css
  src/pages/AdminApplyPage.jsx
  src/pages/Apply.module.css
  src/pages/ApplyPage.jsx
Labels: :recycle: Refactor code

#60 ✨ Feat : 지원서 페이지 임시저장 및 제출 기능 api 연동
  src/api/applyAPI.js
  src/components/applicationForm/AnswerSection.jsx
  src/components/applicationForm/AnswerSection.module.css
  src/components/applicationForm/HeaderSection.jsx
  src/components/applicationForm/HeaderSection.module.css
  src/constants/applicationForm/formConstants.js
  src/hooks/useApplyHook.js
  src/store/useStore.js
Labels: enhancement

#62 🚚 Rename: 파일 위치 변경 및 경로 수정
  src/components/aboutPage/Babylion.jsx
  src/components/aboutPage/Card.jsx
  src/components/aboutPage/Chairman.jsx
  src/components/aboutPage/Management.jsx
  src/components/aboutPage/aboutPage.module.css
  src/components/aboutPage/card.module.css
  src/components/adminAboutPage/AddImage.jsx
  src/components/adminAboutPage/Generation.jsx
  src/components/adminAboutPage/Registration.jsx
  src/components/adminAboutPage/generation.module.css
  src/components/adminAboutPage/registration.module.css
  src/components/recruitPage/Question.jsx
  src/components/recruitPage/RecruitMain.jsx
  src/components/recruitPage/Requirements.jsx
  src/components/recruitPage/Schedule.jsx
  src/components/recruitPage/question.module.css
  src/components/recruitPage/recruitMain.module.css
  src/components/recruitPage/requirements.module.css
  src/components/recruitPage/schedule.module.css
  src/components/resultPage/CheckResult.jsx
  src/components/resultPage/FailPage.jsx
  src/components/resultPage/PassPage.jsx
  src/components/resultPage/checkResult.module.css
  src/components/resultPage/failPage.module.css
  src/components/resultPage/passPage.module.css
Labels: 🚚 Rename

#72 🐛 Fix : api변동에 따른 api 요청 로직 수정
  src/api/applyAPI.js
  src/hooks/useApplyHook.js
Labels: enhancement

#73 ✨ Feat : freamer-motion으로 각 페이지 렌더링 애니메이션 생성
  src/layouts/AnimationLayout.jsx
Labels: enhancement

#74 ✨ Feat : 관리자 지원서 모아보기 페이지 제작
  src/api/adminApplyAPI.js
  src/components/adminApply/Generation.jsx
  src/components/adminApply/HeaderContainer.jsx
  src/components/adminApply/HeaderContainer.module.css
  src/components/adminApply/TableContainer.jsx
  src/components/adminApply/TableContainer.module.css
  src/hooks/useAdminApplyHook.js
  src/pages/AdminApplyPage.jsx
  src/store/useStore.js
Labels: enhancement

#77 ✨ Feat : [관리자] 특정 지원자의 지원서 확인 페이지 제작
  src/api/adminApplyAPI.js
  src/components/adminApply/FormBody.jsx
  src/components/adminApply/FormBody.module.css
  src/components/adminApply/TableContainer.jsx
  src/components/adminApply/ViewForm.jsx
  src/components/adminApply/ViewFormHeader.jsx
  src/hooks/useAdminApplyHook.js
  src/hooks/useApplyHook.js
  src/router/Routes.jsx
Labels: enhancement

#79 ✨ Feat : 내 지원서 확인하기 페이지 구현
  src/api/adminApplyAPI.js
  src/hooks/useAdminApplyHook.js
  src/router/Routes.jsx
Labels: enhancement

#82 ✨ Feat : 지원서 모아보기 페이지 트랙별 분류 기능 추가
  src/api/adminApplyAPI.js
  src/components/adminApply/FormBody.jsx
  src/components/adminApply/FormBody.module.css
  src/components/adminApply/Generation.jsx
  src/components/adminApply/HeaderContainer.jsx
  src/components/adminApply/TableContainer.jsx
  src/components/adminApply/ViewForm.jsx
  src/components/adminApply/ViewFormHeader.jsx
  src/constants/adminApplyConst/index.js
  src/hooks/useAdminApplyHook.js
  src/store/useStore.js
Labels: enhancement

#68 ✨Feat: 로그인 / 회원가입 - 로직 수정 & UI 수정
  package-lock.json
  src/components/login/LoginForm.jsx
  src/components/login/LoginForm.module.css
  src/components/login/LoginFormContainer.module.css
  src/components/login/Signup.module.css
  src/components/signup/ConsentTable.jsx
  src/components/signup/SignupSection.module.css
  src/components/signup/SignupSection1.jsx
  src/components/signup/SignupSection2.jsx
  src/constants/validationSchema/index.js
  src/utils/inputOnChange.js
  src/utils/register.js
Labels: enhancement

#89 🎨 Design : 사용자 정보에 따른 헤더 텍스트 변경 기능 추가 및 버그 수정
  src/api/adminApplyAPI.js
  src/api/applyAPI.js
  src/components/adminApply/FormBody.jsx
  src/components/adminApply/TableContainer.jsx
  src/components/adminApply/ViewForm.jsx
  src/hooks/useAdminApplyHook.js
  src/hooks/useApplyHook.js
  src/router/Routes.jsx
Labels: enhancement

#99 💄 API : 학기 선택 버튼 정적 변수->api 데이터로 변경
  src/api/adminApplyAPI.js
  src/components/adminApply/Generation.jsx
  src/hooks/useAdminApplyHook.js
Labels: enhancement
