Repository LikeLion-SKU/likelion-homepage-fe, pull requests merged in 2025-02, with the labels that each got.

#117 Fix : 오류 수정
  src/components/applicationForm/AnswerSection.jsx
  src/components/applicationForm/Application.jsx
  src/components/applicationForm/Application.module.css
  src/hooks/useApplyHook.js
Labels: enhancement, :recycle: Refactor code

#115 ✨ Feat: 모바일 스와이프 전환 및 화살표 표시 조건 추가
  src/components/ProjectPage/EditImagePreview.jsx
  src/components/ProjectPage/ImagePreview.jsx
  src/components/ProjectPage/ProjectPageLayout.jsx
  src/components/ProjectPage/ProjectPageLayout.module.css
Labels: enhancement, :recycle: Refactor code

#125 [Feat] : 404예외처리 및 디자인 수정
  src/api/adminApplyAPI.js
  src/components/adminApply/ViewForm.jsx
  src/components/applicationForm/HeaderSection.module.css
  src/hooks/useAdminApplyHook.js
Labels: enhancement

#127 🎨Design: imageUploadButton margin-top 추가
  src/components/ProjectPage/ImagePreview.jsx
  src/components/ProjectPage/ImagePreview.module.css
  src/components/ProjectPage/NewProjectForm.jsx
Labels: enhancement

#138 🐛 Fix : api 변동사항에 따른 엔드포인트 변경
  src/api/adminApplyAPI.js
  src/hooks/useAdminApplyHook.js
Labels: enhancement

#143 🐛 Fix : 관리자페이지 예외처리 location.href => alert로 변경
  src/api/adminApplyAPI.js
Labels: enhancement

#158 ♻️ Refactor: result url접근 방지
  src/components/recruitPage/RecruitMain.jsx
  src/components/recruitPage/Requirements.jsx
  src/components/resultPage/CheckResult.jsx
  src/components/resultPage/FailPage.jsx
Labels: :recycle: Refactor code

#142 ✨ Feat: 로딩 스피너 추가
  src/components/ProjectPage/ProjectDetail.jsx
  src/components/ProjectPage/ProjectDetail.module.css
Labels: enhancement

#167 [Feat] : 지원서 제출 페이지, 지원서 확인하기 페이지 수정
  src/api/applyAPI.js
  src/components/adminApply/FormBody.jsx
  src/components/adminApply/FormBody.module.css
  src/components/applicationForm/AnswerSection.jsx
  src/components/applicationForm/Application.jsx
  src/components/applicationForm/HeaderSection.jsx
  src/components/applicationForm/HeaderSection.module.css
  src/hooks/useAdminApplyHook.js
  src/hooks/useApplyHook.js
Labels: enhancement, :recycle: Refactor code

#162 Refactor/result page
  src/components/mypage/Navigation.jsx
  src/components/recruitPage/RecruitMain.jsx
  src/components/resultPage/FailPage.jsx
Labels: :recycle: Refactor code

#170 Refactor/result page
  src/components/adminAboutPage/Generation.jsx
  src/components/recruitPage/question.module.css
  src/components/resultPage/PassPage.jsx
Labels: :recycle: Refactor code

#171 🐛 Fix : getDeadLine 엔드포인트 변경 및 onChange 버튼 색 변경 버그 수정
  src/api/applyAPI.js
  src/hooks/useApplyHook.js
Labels: enhancement

#175 🐛 Fix : 400 에러 처리 코드 추가
  src/components/applicationForm/Application.module.css
  src/hooks/useApplyHook.js
Labels: enhancement

#186 🐛 Fix : 지원서 작성 1페이지 에러 처리를 위해 api 변경
  src/hooks/useApplyHook.js
Labels: enhancement
